services:
  risktrace.api:
    container_name: risktrace.api
    build:
      context: .
      dockerfile: src/RiskTrace.Api/Dockerfile
    depends_on:
      risktrace.db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      Database__Provider: PostgreSQL
      ConnectionStrings__DefaultConnection: Host=risktrace.db;Port=5432;Database=risktrace;Username=postgres;Password=postgres
    ports:
      - "8080:8080"

  risktrace.db:
    container_name: risktrace.db
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: risktrace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d risktrace"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - risktrace-postgres:/var/lib/postgresql/data

volumes:
  risktrace-postgres:
